version: "3.5"

services:
    mp-ecommerce:
        image: node:lts-alpine
        command: sh -c "npm install && npm run debug"
        working_dir: /app
        ports:
            - "3000:3000"
            - "9229:9229"
        env_file:
            - ./app.env
        volumes:
            - .:/app
